### ISSUE TITLE
Framework version issue, please help

### ISSUE THREAD

**Issue by DiLDoST** [DurtyFree/GTA-SA-ScriptHook#4]
Am having troubles with the framework version, it's not working properly, i tried a very old version from somewhere else idk, is working, but your this latest build isn't working, please help buddy.

Please fix it, it will start working again if your project is migrated to v3.5 . I tested somehow. And bro am such a fan of your work, can i contribute in your project too please???

Log:

```2020-12-30 01:13:37 - INFO: DBNetwork GTA .NET Scripting API (built on 2010-1-29 14:59)
2020-12-30 01:13:37 - INFO: compiled for GTA: San Andreas
2020-12-30 01:13:37 - INFO: Game version: 1.0
2020-12-30 01:13:37 - WARNING: Exception: System.BadImageFormatException: Could not load file or assembly 'GTAScriptAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.
2020-12-30 01:13:37 - ERROR: System.BadImageFormatException: This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded. (Exception from HRESULT: 0x8013101B)
   at System.Reflection.Assembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at GTA.ScriptLoader.LoadAssemblies(String folder, String filter)
   at GTA.ScriptLoader.LoadScripts()
   at GoManaged()

**Comment by DurtyFree** [comment]
You can just clone the repo and build it with .NET 3.5 if you need it

**Comment by DiLDoST** [comment]
> You can just clone the repo and build it with .NET 3.5 if you need it

Bro i tried but my IDE doesn't supports c or cpp but only C#, because am using SharpDevelop. I cant use any other IDE because of the internet speed in my city, it's only 5kbps. Am suffering alot in life because of this f*in internet. Please help me by building it for me (the .Net v3.5) please. I'll appreciate it. Or if you can reprogram the GTAScriptHook in C# anyhow, then i can fully contribute too. For now i can only contribute in GTAScriptAPI. Bro i love your work and i appreciate it. I hope you'll help me anyhow ❤️❤️

And bro i also wanted you to improve something like GTA.World.GetAllPeds does not include Ballas, idk why, it's very shocking that why they are not in the list. And bro your GTA.Cheats also needs to be improved (i created a new one if you want me to show it to you, not much but some usefull changes). And bro also add some new improvements like how to get peds of a vehicle, how to change ped anim, how to get ped's target, how to give user a weapon (as i tried everything but none of them are working like Player.Weapons.Misc_Camera : .Load , .Select but the user still does not gets it) and even i tried spawning a weapon using Pickup, it spawns but user cant pick it up nor the OnPickUp even is being called while Player's position == Pickup's Position. I have must things to suggest bro but am afraid if you will add these or not. Because every dev just ignores my suggestions. Even though am also a dev but i have no importance 🥺 

I'll be Waiting for your answer buddy please don't ignore my suggestions as i respect you as an ideal to me ❤️❤️❤️

**Comment by DiLDoST** [comment]
Buddy! I have founded and tested alot of opcodes which you can use in your project, they include IS_PED_SHOOTING, GET_VEHICLE_DRIVER, EXPLODE_PED_HEAD, IS_MODEL_HELI/PLANE/BOAT/etc, GIVE_WEAPON_TO_PED (The most useful, which isn't yet on your project) and much more, i have tested nearly 27 of them but i think i still have a list of more than 100 to test. Can i share them here in comments on anywhere? They are formatted the same way as you did, the comments make them absolutely clear on how to use them like:
HAS_PED_SPOTTED_PED =0x0..., // pHandle, pHandle => bool

Can i share with you?

**Comment by xb-bx** [comment]
I'm have the same issue but on my pc installed .net framework 4.8

**Comment by DiLDoST** [comment]
Brother can u just make a little time and make a v3.5 build for us pleeeeeaaassseee? My IDE doesn't supports C or C++, it's just C#, that's why i Can't do that na. Pleeeeeaaassseee it won't take much. Just upload for us na Please bro Please we request you 🥺

**Comment by DiLDoST** [comment]
> I'm have the same issue but on my pc installed .net framework 4.8

Bro request him kindly, he loooks so busy, doesn't has a min to spend 🤧

**Comment by Mell01337** [comment]
> 
> 
> You can just clone the repo and build it with .NET 3.5 if you need it

Tried that, mscorlib of v3.5 does not support some of the ScriptAPI Functions.
Receiving the same error with newer runtime, also tried to just use the .cs script or compile everything in v4.8.
Very sad that it's not working since I really would like to develop scripts in c#.
Maybe you have an idea or could check whats the problem.
Thanks and best regards

**Comment by Samthapa76** [comment]
i have doubt 

2024-06-11 22:39:43 - INFO: DBNetwork GTA .NET Scripting API (built on 2010-1-29 14:59)
2024-06-11 22:39:43 - INFO: compiled for GTA: San Andreas
2024-06-11 22:39:43 - INFO: Game version: 1.0
2024-06-11 22:39:43 - ERROR: System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\_Fave_Game\_Real_Vision_Sa\modloader\_total_gang_mods_\scripts'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at GTA.ScriptLoader.LoadAssemblies(String folder, String filter)
   at GTA.ScriptLoader.LoadScripts()
   at GoManaged()

is it stealer ?
